CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ChangeEvents" (
    "ChangeEventID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "DateRecorded" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ChangeEvents" PRIMARY KEY ("ChangeEventID")
);

CREATE TABLE "Persons" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "MiddleName" character varying(100) NULL,
    "LastName" character varying(100) NOT NULL,
    "DateOfBirth" timestamp without time zone NOT NULL,
    "Gender" character varying(1) NOT NULL,
    "ContactNo" character varying(20) NULL,
    "Email" character varying(100) NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "UpdatedById" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Persons" PRIMARY KEY ("Id")
);

CREATE TABLE "ChangeLogs" (
    "ChangeLogID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ChangeEventID" bigint NOT NULL,
    "TableName" text NULL,
    "ColumnName" text NULL,
    "RowID" text NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "Operation" text NULL,
    CONSTRAINT "PK_ChangeLogs" PRIMARY KEY ("ChangeLogID"),
    CONSTRAINT "FK_ChangeLogs_ChangeEvents_ChangeEventID" FOREIGN KEY ("ChangeEventID") REFERENCES "ChangeEvents" ("ChangeEventID") ON DELETE CASCADE
);

CREATE TABLE "Planes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "AirportId" integer NOT NULL,
    "IsAvailable" boolean NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "UpdatedById" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Planes" PRIMARY KEY ("Id")
);

CREATE TABLE "Bookings" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp without time zone NOT NULL,
    "IsConfirmed" boolean NOT NULL,
    "BookingTypeId" integer NOT NULL,
    "TutorId" integer NULL,
    "PlaneId" integer NULL,
    "StudentId" integer NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "UpdatedById" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_Planes_PlaneId" FOREIGN KEY ("PlaneId") REFERENCES "Planes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UserLogins" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(50) NOT NULL,
    "Password" text NOT NULL,
    "Salt" text NULL,
    "Role" text NOT NULL,
    "PersonId" integer NOT NULL,
    "TutorId" integer NULL,
    "StudentId" integer NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "UpdatedById" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserLogins_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Airports" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "IsAvailable" boolean NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "UpdatedById" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Airports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Airports_UserLogins_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Airports_UserLogins_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BookingTypes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(300) NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "UpdatedById" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_BookingTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BookingTypes_UserLogins_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BookingTypes_UserLogins_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Students" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "School" character varying(100) NULL,
    "IDNumber" character varying(20) NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "UpdatedById" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Students" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Students_UserLogins_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Students_UserLogins_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tutors" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AvailableDateFrom" timestamp without time zone NOT NULL,
    "AvailableDateTo" timestamp without time zone NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "UpdatedById" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Tutors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tutors_UserLogins_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Tutors_UserLogins_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Airports_CreatedById" ON "Airports" ("CreatedById");

CREATE INDEX "IX_Airports_UpdatedById" ON "Airports" ("UpdatedById");

CREATE INDEX "IX_Bookings_BookingTypeId" ON "Bookings" ("BookingTypeId");

CREATE INDEX "IX_Bookings_CreatedById" ON "Bookings" ("CreatedById");

CREATE INDEX "IX_Bookings_PlaneId" ON "Bookings" ("PlaneId");

CREATE INDEX "IX_Bookings_StudentId" ON "Bookings" ("StudentId");

CREATE INDEX "IX_Bookings_TutorId" ON "Bookings" ("TutorId");

CREATE INDEX "IX_Bookings_UpdatedById" ON "Bookings" ("UpdatedById");

CREATE INDEX "IX_BookingTypes_CreatedById" ON "BookingTypes" ("CreatedById");

CREATE INDEX "IX_BookingTypes_UpdatedById" ON "BookingTypes" ("UpdatedById");

CREATE INDEX "IX_ChangeLogs_ChangeEventID" ON "ChangeLogs" ("ChangeEventID");

CREATE INDEX "IX_Planes_AirportId" ON "Planes" ("AirportId");

CREATE INDEX "IX_Planes_CreatedById" ON "Planes" ("CreatedById");

CREATE INDEX "IX_Planes_UpdatedById" ON "Planes" ("UpdatedById");

CREATE INDEX "IX_Students_CreatedById" ON "Students" ("CreatedById");

CREATE INDEX "IX_Students_UpdatedById" ON "Students" ("UpdatedById");

CREATE INDEX "IX_Tutors_CreatedById" ON "Tutors" ("CreatedById");

CREATE INDEX "IX_Tutors_UpdatedById" ON "Tutors" ("UpdatedById");

CREATE INDEX "IX_UserLogins_PersonId" ON "UserLogins" ("PersonId");

CREATE INDEX "IX_UserLogins_StudentId" ON "UserLogins" ("StudentId");

CREATE INDEX "IX_UserLogins_TutorId" ON "UserLogins" ("TutorId");

ALTER TABLE "Planes" ADD CONSTRAINT "FK_Planes_Airports_AirportId" FOREIGN KEY ("AirportId") REFERENCES "Airports" ("Id") ON DELETE CASCADE;

ALTER TABLE "Planes" ADD CONSTRAINT "FK_Planes_UserLogins_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE;

ALTER TABLE "Planes" ADD CONSTRAINT "FK_Planes_UserLogins_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE;

ALTER TABLE "Bookings" ADD CONSTRAINT "FK_Bookings_BookingTypes_BookingTypeId" FOREIGN KEY ("BookingTypeId") REFERENCES "BookingTypes" ("Id") ON DELETE CASCADE;

ALTER TABLE "Bookings" ADD CONSTRAINT "FK_Bookings_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE;

ALTER TABLE "Bookings" ADD CONSTRAINT "FK_Bookings_Tutors_TutorId" FOREIGN KEY ("TutorId") REFERENCES "Tutors" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Bookings" ADD CONSTRAINT "FK_Bookings_UserLogins_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE;

ALTER TABLE "Bookings" ADD CONSTRAINT "FK_Bookings_UserLogins_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "UserLogins" ("Id") ON DELETE CASCADE;

ALTER TABLE "UserLogins" ADD CONSTRAINT "FK_UserLogins_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserLogins" ADD CONSTRAINT "FK_UserLogins_Tutors_TutorId" FOREIGN KEY ("TutorId") REFERENCES "Tutors" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210428114621_Initial_Migration', '5.0.5');

COMMIT;